apiVersion: apps/v1
kind: Deployment
metadata:
  name: citest-a-deploy
  namespace: citest
  labels:
    app: citest-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: citest-a
  template:
    metadata:
      labels:
        app: citest-a
    spec:
      containers:
        - name: citest-a
          image: gcr.io/test-teraform-259205/citest:a
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: citest-a-svc
  namespace: citest
spec:
  type: NodePort
  selector:
    app: citest-a
  ports:
    - port: 8080
      targetPort: 8080
