apiVersion: apps/v1
kind: Deployment
metadata:
  name: citest-a-deploy
  labels:
    app: citest-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: citest-a
  template:
    metadata:
      labels:
        app: citest-a
    spec:
      containers:
        - name: citest-a
          image: gcr.io/test-teraform/citest@sha256:5ff2530fe55fd190124925e699a7407f98b51b2569e543210f58220a8e5fb9a3
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: citest-a-svc
spec:
  type: NodePort
  selector:
    app: citest-a
  ports:
    - port: 8080
      targetPort: 8080
