apiVersion: apps/v1
kind: Deployment
metadata:
  name: citest-b-deploy
  labels:
    app: citest-b
spec:
  replicas: 3
  selector:
    matchLabels:
      app: citest-b
  template:
    metadata:
      labels:
        app: citest-b
    spec:
      containers:
        - name: citest-b
          image: gcr.io/test-teraform/citest:b
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: citest-b-svc
spec:
  type: NodePort
  selector:
    app: citest-b
  ports:
    - port: 8080
      targetPort: 8080
