apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: citest-ingress
  namespace: citest
  annotations:
    kubernetes.io/ingress.global-static-ip-name: citest-ingress
    networking.gke.io/managed-certificates: citest-a-ca,citest-b-ca
spec:
  rules:
    - host: aaa.citest.tk
      http:
        paths:
          - backend:
             serviceName: citest-a-svc
             servicePort: 8080
    - host: bbb.citest.tk
      http:
        paths:
          - backend:
              serviceName: citest-b-svc
              servicePort: 8080
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: citest-a-ca
  namespace: citest
spec:
  domains:
    - aaa.citest.tk
---
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: citest-b-ca
  namespace: citest
spec:
  domains:
    - bbb.citest.tk
