apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: citest-concourse
nameSuffix: -concourse
bases:
  - ../../base
images:
  - name: gcr.io/citest1/web/citest
    digest: sha256:746a5b87d6900bfbcaa82214c402655008da49ab8e597bd4e21215739683b948
