apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: citest-concourse
nameSuffix: -concourse
bases:
  - ../../base
images:
  - name: gcr.io/citest1/web/citest
    newTag: sha256:0d4f2cdf79a90b3d11e93e698fca9470a0dbbdd526a4adaf31647ae0e48ae2df
