resource_types:
  - name: kubernetes
    type: docker-image
    source:
      repository: zlabjp/kubernetes-resource
      tag: "1.14"
resources:
  - name: kubernetes
    type: kubernetes
    source:
      kubeconfig: ((kubeconfig))
  - name: ci-test-release
    type: git
    source:
      uri: https://github.com/tigerfdev/ci-test-release.git
      branch: concourse
      paths:
        - manifests/citest

jobs:
  - name: ci-test-release
    public: true
    serial: true
    plan:
      - get: ci-test-release
        trigger: true
      - put: kubernetes
        params:
          kubectl: apply -k ci-test-release/manifests/citest/kustomize/overlays/concourse
          wait_until_ready: 0
