resources:
  - name: citest
    type: git
    source:
      uri: https://github.com/tigerfdev/ci-test.git
  - name: citest-release
    type: git
    source:
      uri: https://github.com/tigerfdev/ci-test-release.git
      branch: concourse
      username: tigerfdev
      password: ((git-key))
  - name: docker
    type: docker-image
    source:
      repository: gcr.io/citest1/web/citest
      tag: concourse
      username: _json_key
      password: ((gcr-key))

jobs:
  - name: citest-build
    public: true
    serial: true
    plan:
      - get: citest
        trigger: true
      - task: write-tag-file
        config:
          platform: linux
          image_resource:
            type: registry-image
            source: { repository: busybox }
          outputs:
            - name: workspace
          run:
            path: sh
            args:
              - -exc
              - echo "concourse" > workspace/tag
      - put: docker
        params:
          build: citest/citest
          tag_file: workspace/tag

  - name: manifest-updete
    public: true
    serial: true
    plan:
      - get: docker
        trigger: true
        passed: [citest-build]
      - get: citest-release
      - task: manifest-updete
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: concourse/git-resource}
          inputs:
            - name: docker
            - name: citest-release
          outputs:
            - name: citest-release-modified
          run:
            path: sh
            args:
              - -exc
              - |
                git config --global user.name "concourse"
                git config --global user.email "concourse@no.reply"

                git clone citest-release citest-release-modified
                cd citest-release-modified
                git pull
                sed -i -e "s/digest: .*$/digest: $(cat ../docker/digest)/" manifests/citest/kustomize/overlays/concourse/kustomization.yaml
                git add ./manifests/citest/kustomize/overlays/concourse/kustomization.yaml
                if ! git diff-index --quiet HEAD --; then
                  git commit -m "CI: update manifests"
                else
                  echo "No changes to commit. skipping"
                fi
      - put: citest-release
        params:
          repository: citest-release-modified
          rebase: true
