steps:
  - name: gcr.io/cloud-builders/kubectl
    id: Deploy
    args:
      - apply
      - -k
      - manifests/citest/kustomize/overlays/cloudbuild
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast1-a
      - CLOUDSDK_CONTAINER_CLUSTER=my-gke-cluster
